# NB: this suppose that a postgresql container is running
# on the host and that its gateway is 172.17.0.1
---
apiVersion: v1
data:
  database: {{ printf "ogscloud" | b64enc }}
  hostname: {{ printf "ogsdocker-postgresql" | b64enc }}
  username: {{ printf "admin" | b64enc }}
  password: {{ printf "pass@1234" | b64enc }}
  port: {{ printf "5432" | b64enc }}
  schema: {{ printf "config" | b64enc }}

kind: Secret
type: Opaque
metadata:
  name: 'gs-cloud-jdbc-db'
