apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}-rest
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    gs-service: rest
spec:
  type: {{ .Values.geoserver.rest.service.type }}
  ports:
    - port: {{ .Values.geoserver.rest.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "geoserver.selectorLabels" . | nindent 4 }}
    gs-service: rest
