apiVersion: v2
appVersion: '1.0-RC27'
#appVersion: '1.0-SNAPSHOT'
description: A Helm chart for Geoserver-cloud
name: geoservercloud
version: 0.0.46
dependencies:
  - name: 'rabbitmq'
    version: 8.28.1
    repository: 'https://charts.bitnami.com/bitnami'
    condition: rabbitmq.enabled
  - name: 'postgresql'
    version: 10.16.2
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
