postgresql:
  auth:
    enablePostgresUser: true
    postgresPassword: 'admin123'

  primary:
    initdb:
      scripts:
        init.sql: |
          CREATE DATABASE ogscloud;
          CREATE ROLE admin WITH LOGIN PASSWORD 'pass@1234';
          GRANT ALL PRIVILEGES ON DATABASE ogscloud TO admin;
          ALTER DEFAULT PRIVILEGES GRANT USAGE ON SEQUENCES TO admin;
          \c ogscloud
          CREATE EXTENSION postgis;
          CREATE SCHEMA config ;
          CREATE SCHEMA data;
          ALTER SCHEMA config OWNER TO admin;
          ALTER SCHEMA data OWNER TO admin;

rabbitmq:
  enabled: true
  resources:
    limits:
      cpu: 2
      memory: 512Mi
    requests:
      cpu: 0.1
      memory: 512Mi

  auth:
    username: geoserver
    erlangCookie: cookie

  persistence:
    enabled: false

additionalVolumes: &additional-volumes
  cache:
    persistentVolumeClaim:
      claimName: gs-cloud-gwc-cache-nfs-claim
  geodata:
    configMap:
      name: cm-jndi-geodata

additionalVolumeMounts: &additional-volume-mounts
  /mnt/cache:
    name: 'cache'
  /custom/geodata:
    name: 'geodata'
    readOnly: true

env: &env-override
  RABBITMQ_HOST:
    value: 'ogsdocker-rabbitmq'
  RABBITMQ_USER:
    value: 'geoserver'
  RABBITMQ_PASSWORD:
    type: secret
    name: 'ogsdocker-rabbitmq'
    key: 'rabbitmq-password'
  SPRING_PROFILES_ACTIVE:
    value: standalone,jdbcconfig
  GEOWEBCACHE_CACHE_DIR:
    value: '/mnt/cache'
  JAVA_OPTS:
    value: '$(JAVA_OPTS_DEFAULT) -Dspring.config.additional-location=optional:file:/custom/geodata/jndi.yml'
  JDBCCONFIG_DATABASE:
    type: secret
    name: 'gs-cloud-jdbc-db'
    key: 'database'
  JDBCCONFIG_HOST:
    type: secret
    name: 'gs-cloud-jdbc-db'
    key: 'hostname'
  JDBCCONFIG_USERNAME:
    type: secret
    name: 'gs-cloud-jdbc-db'
    key: 'username'
  JDBCCONFIG_PASSWORD:
    type: secret
    name: 'gs-cloud-jdbc-db'
    key: 'password'
  JDBCCONFIG_PORT:
    type: secret
    name: 'gs-cloud-jdbc-db'
    key: 'port'
  JDBCCONFIG_SCHEMA:
    type: secret
    name: 'gs-cloud-jdbc-db'
    key: 'schema'

additional-stuff: &additional-stuff
  volumes:
    <<: *additional-volumes
  containers:
    spring:
      env:
        <<: *env-override
      volumeMounts:
        <<: *additional-volume-mounts

geoservercloud:
  global:
    profile: standalone,datadir
    image:
      pullPolicy: IfNotPresent
  geoserver:
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/rewrite-target: /$1/web
      enabled: true
      hostGroups:
        host1:
          tls:
            enabled: false
          hosts:
            - gscloud.local
    services:
      gateway:
        ingress:
          enabled: true
          path: /geoserver-cloud/
        <<: *additional-stuff
      webui:
        <<: *additional-stuff
      rest:
        enabled: false
        <<: *additional-stuff
      wms:
        enabled: false
        replicaCount: 1
        <<: *additional-stuff
      wcs:
        enabled: false
        <<: *additional-stuff
      wfs:
        enabled: false
        replicaCount: 1
        <<: *additional-stuff
      gwc:
        enabled: false
        replicaCount: 1
        <<: *additional-stuff
