apiVersion: v1
data:
  DATABASE_NAME: {{ .Values.postgresql.postgresqlDatabase | b64enc }}
  HOST: {{ printf "%s-%s" .Release.Name "postgresql" | b64enc }}
  ROLE: {{ .Values.postgresql.postgresqlUsername | b64enc }}
  PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.geoserver.database.secretConfig }}-{{ include "geoserver.fullname" . }}
  #namespace: sig-dev
type: Opaque

