{{- if .Values.geoserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geoserver.serviceAccountName" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
  {{- with .Values.geoserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
